functionsDirectory = "/home/user/Doubao/chats/38443669086188802/qimendun-repo/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/user/Doubao/chats/38443669086188802/qimendun-repo/public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "/home/user/Doubao/chats/38443669086188802/qimendun-repo/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]